- name: usage of variables from file
  hosts: local
  connection: local
  vars_files:
  - variables.yml
  tasks:
  - name: printing capital of country
    ansible.builtin.debug:
      msg: "name of country is {{ country }}, capital is {{ capital }}"
